version: '3'

services:
  mssql:
    image: charlesschneider/smartbuild
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mssql
    environment:
      - ACCEPT_EULA="Y"
      - SA_PASSWORD=Pass@word
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
     - mssql:/var/opt/mssql/data

volumes:
    mssql:
     